import 'dart:convert';
import 'dart:io';

import 'package:ai_tavern/models/save_slot.dart';
import 'package:ai_tavern/models/trpg_dice_models.dart';
import 'package:ai_tavern/models/trpg_models.dart';
import 'package:ai_tavern/repositories/save_repository.dart';
import 'package:ai_tavern/repositories/trpg_session_repository.dart';
import 'package:ai_tavern/services/storage_service.dart';
import 'package:ai_tavern/services/trpg/campaign_service.dart';
import 'package:ai_tavern/services/trpg/dice_service.dart';
import 'package:ai_tavern/services/trpg/trpg_session_service.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:sqflite_common_ffi/sqflite_ffi.dart';

void main() {
  group('TRPG core', () {
    late Directory directory;
    late StorageService storage;
    late TRPGSessionRepository repository;

    setUp(() async {
      directory = await Directory.systemTemp.createTemp('ai_tavern_trpg_');
      storage = StorageService();
      await storage.initialize(
        databasePath: '${directory.path}${Platform.pathSeparator}test.db',
      );
      repository = TRPGSessionRepository(storage);
    });

    tearDown(() async {
      await storage.close();
      await directory.delete(recursive: true);
    });

    test('creates, serializes, restores and deletes a solo session', () async {
      final service = TRPGSessionService(repository);
      final campaign = const CampaignService().builtInCampaigns.last;
      final session = await service.createSolo(
        campaign: campaign,
        playerName: '测试玩家',
        characterName: '晨歌',
        characterBackground: '来自海港的调查员',
        stats: const {'STR': 9, 'DEX': 12, 'INT': 15, 'PER': 14, 'CHA': 10},
        gmProviderConfigRef: 'deepseek-profile',
        rulePackage: DiceRulePackageType.dnd,
      );

      final json = session.toJson();
      final roundTrip = TRPGSession.fromJson(json);
      expect(roundTrip.playerCharacters.single.name, '晨歌');
      expect(roundTrip.gmState.privateNotes, isNotEmpty);
      expect(roundTrip.schemaVersion, trpgSchemaVersion);
      expect(
        roundTrip.ruleState.diceSettings.rulePackage,
        DiceRulePackageType.dnd,
      );

      final restored = await service.restore(session.id);
      expect(restored, isNotNull);
      expect(restored!.chatHistory, hasLength(1));
      expect(restored.chatHistory.single.content, contains('【世界观】'));
      expect(restored.chatHistory.single.content, contains('【主要人物】'));
      expect(restored.chatHistory.single.content, contains('【正在发生】'));
      expect(restored.chatHistory.single.content, contains('晨歌（玩家角色）'));
      expect(restored.eventLog.single.payload['scene'], isA<Map>());
      expect(restored.campaignState.activeQuests, isNotEmpty);

      await service.delete(session.id);
      expect(await service.restore(session.id), isNull);
    });

    test('D20 is generated by program and recorded in history', () async {
      final service = TRPGSessionService(repository);
      final session = await service.createSolo(
        campaign: const CampaignService().builtInCampaigns.first,
        playerName: '玩家',
        characterName: '骰手',
        characterBackground: '',
        stats: const {'STR': 10},
      );
      final dice = DiceService();
      for (var i = 0; i < 100; i++) {
        final roll = dice.roll(
          sides: 20,
          playerId: session.players.single.playerId,
        );
        expect(roll.total, inInclusiveRange(1, 20));
      }
      final roll = dice.roll(
        sides: 20,
        playerId: session.players.single.playerId,
      );
      final updated = dice.record(session, roll);
      expect(updated.ruleState.diceHistory.single.total, roll.total);
      expect(updated.eventLog.last.type, TRPGEventType.diceRoll);
      expect(updated.chatHistory.last.messageType, TRPGMessageType.diceMessage);
    });

    test('room owner and AI host provider can be different players', () async {
      var session = createLocalMultiplayerSession(
        title: '本地测试房',
        ownerName: '房主 A',
      );
      final provider = TRPGPlayer(
        playerId: 'player-c',
        displayName: '玩家 C',
        joinedAt: DateTime.now(),
      );
      session = session.copyWith(players: [...session.players, provider]);
      final changed = TRPGSessionService(repository).changeAIHostProvider(
        session,
        session.aiHostConfig.copyWith(
          mode: AIHostMode.selectedPlayer,
          providerPlayerId: provider.playerId,
          status: AIHostStatus.pending,
        ),
      );
      await repository.upsert(changed);
      final restored = await repository.getById(changed.id);

      expect(restored!.roomOwnerPlayerId, isNot(provider.playerId));
      expect(restored.aiHostConfig.providerPlayerId, provider.playerId);
      expect(restored.aiHostConfig.status, AIHostStatus.pending);
      expect(restored.gmStateSnapshot.currentScene, changed.currentScene);
    });

    test('database v6 keeps legacy tavern saves beside TRPG saves', () async {
      final tavernRepository = SaveRepository(storage);
      final legacy = SaveSlot.create(name: '旧酒馆存档', playerName: '旧玩家');
      await tavernRepository.upsert(legacy);

      await TRPGSessionService(repository).createSolo(
        campaign: const CampaignService().builtInCampaigns.first,
        playerName: '新玩家',
        characterName: '新角色',
        characterBackground: '',
        stats: const {'STR': 10},
      );

      final tavernSaves = await tavernRepository.getAll();
      final trpgSaves = await repository.getAll(mode: TRPGMode.solo);
      expect(tavernSaves.single.id, legacy.id);
      expect(trpgSaves, hasLength(1));
    });

    test('legacy v5 database upgrades without losing tavern row', () async {
      final legacyPath =
          '${directory.path}${Platform.pathSeparator}legacy-v5.db';
      sqfliteFfiInit();
      final legacyDb = await databaseFactoryFfi.openDatabase(
        legacyPath,
        options: OpenDatabaseOptions(
          version: 5,
          onCreate: (db, _) async {
            await db.execute('''
              CREATE TABLE save_slots (
                id TEXT PRIMARY KEY,
                name TEXT NOT NULL,
                player_name TEXT NOT NULL,
                message_count INTEGER NOT NULL DEFAULT 0,
                updated_at INTEGER NOT NULL,
                last_played_at INTEGER NOT NULL,
                payload TEXT NOT NULL
              )
            ''');
          },
        ),
      );
      final oldSave = SaveSlot.create(name: '升级前存档');
      await legacyDb.insert('save_slots', {
        'id': oldSave.id,
        'name': oldSave.name,
        'player_name': oldSave.playerName,
        'message_count': 0,
        'updated_at': oldSave.updatedAt.millisecondsSinceEpoch,
        'last_played_at': oldSave.lastPlayedAt.millisecondsSinceEpoch,
        'payload': jsonEncode(oldSave.toJson()),
      });
      await legacyDb.close();

      final upgraded = StorageService();
      await upgraded.initialize(databasePath: legacyPath);
      final tables = await upgraded.database.rawQuery(
        "SELECT name FROM sqlite_master WHERE type='table' AND name='trpg_sessions'",
      );
      expect(tables, hasLength(1));
      expect(
        await upgraded.database.query(
          'save_slots',
          where: 'id = ?',
          whereArgs: [oldSave.id],
        ),
        hasLength(1),
      );
      await upgraded.close();
    });
  });
}
