import 'package:flutter/material.dart';
import 'theme_definition.dart';
import 'theme_craft.dart';

abstract final class ThemeCatalog {
  static const featuredIds = ['classic_tavern', 'cyber_neon', 'ink_oriental'];
  static List<ThemeDefinition> get featured => featuredIds.map(byId).toList();
  static List<ThemeDefinition> get characters =>
      themes.where((d) => d.category == 'character_theme').toList();
  static List<ThemeDefinition> get showcase => [...characters, ...featured];
  static const themes = <ThemeDefinition>[
    ThemeDefinition(
      id: 'knight_oath_mooncourt',
      name: '誓约之剑 · 王之庭院',
      description: 'Saber 融入月夜王庭，披风、月光与金线连成整页背景。',
      category: 'character_theme',
      mode: SkinMode.dark,
      seed: Color(0xffdec48a),
      background: Color(0xff070f20),
      backgroundImage: 'assets/themes/knight_oath_mooncourt/bg_saber_wide.png',
      chatBackgroundImage:
          'assets/themes/knight_oath_mooncourt/bg_saber_wide.png',
      portraitBackgroundImage:
          'assets/themes/knight_oath_mooncourt/bg_saber_mobile.png',
      immersiveArtwork: true,
      assetManifest: 'assets/themes/knight_oath_mooncourt/manifest.json',
      artworkAlignment: Alignment(.65, -1),
      backgroundBlur: 0,
      backgroundOpacity: .95,
      overlayOpacity: .08,
      pattern: BackgroundPattern.arches,
      radius: 12,
      elevation: 1,
      material: SkinMaterial.oath,
      palette: SkinPalette(
        surface: Color(0xff12243a),
        recessed: Color(0xff0c1b30),
        raised: Color(0xff1c3049),
        text: Color(0xfff2eddf),
        muted: Color(0xffbecbdc),
        line: Color(0xff9f8a60),
        softLine: Color(0xff625c4c),
        accent: Color(0xffdec48a),
        onAccent: Color(0xff172439),
        secondary: Color(0xffa4cdf0),
      ),
      metadata: {
        'collection': '角色主题',
        'coverTitle': '月下王庭',
        'characterName': 'Saber · 阿尔托莉雅',
        'characterCaption': '以此剑，守护心中的誓约。',
        'subtitle': '月下王庭 / 骑士誓约 / 圣杯战争氛围',
        'detail': '月夜古堡 / 细金剑徽 / 深蓝玻璃 / 象牙白信笺',
      },
    ),
    ThemeDefinition(
      id: 'rapi_tactical_command',
      name: '反击战线 · 拉毗指挥室',
      description: '拉毗融入地下战术指挥室，红色扫描光掠过深灰装甲界面。',
      category: 'character_theme',
      mode: SkinMode.dark,
      seed: Color(0xffef3340),
      secondary: Color(0xffdfe5ea),
      background: Color(0xff080a0d),
      backgroundImage: 'assets/themes/rapi_tactical_command/bg_rapi_wide.png',
      chatBackgroundImage:
          'assets/themes/rapi_tactical_command/bg_rapi_wide.png',
      portraitBackgroundImage:
          'assets/themes/rapi_tactical_command/bg_rapi_mobile.png',
      immersiveArtwork: true,
      assetManifest: 'assets/themes/rapi_tactical_command/manifest.json',
      artworkAlignment: Alignment(.78, -.25),
      backgroundBlur: 0,
      backgroundOpacity: .95,
      overlayOpacity: .08,
      pattern: BackgroundPattern.grid,
      radius: 5,
      elevation: 0,
      material: SkinMaterial.tactical,
      animatedBackground: true,
      letterSpacing: .25,
      palette: SkinPalette(
        surface: Color(0xff15191e),
        recessed: Color(0xff0c1014),
        raised: Color(0xff20262d),
        text: Color(0xfff2f3f4),
        muted: Color(0xffaab1b8),
        line: Color(0xff6f2d34),
        softLine: Color(0xff343a40),
        accent: Color(0xffef3340),
        onAccent: Color(0xffffffff),
        secondary: Color(0xffd9e0e5),
      ),
      metadata: {
        'collection': '角色主题',
        'coverTitle': '地面夺还 · 战术待命',
        'characterName': '拉毗 · 反击部队',
        'characterCaption': '指挥官，作战准备已经完成。',
        'subtitle': 'NIKKE / 地下指挥室 / 红黑战术终端',
        'detail': '装甲切角 / 红色扫描线 / 战术瞄准框 / 冷白编号',
      },
    ),
    ThemeDefinition(
      id: 'miku_digital_stage',
      name: '未来音阶 · Miku 数字舞台',
      description: 'Miku 融入青绿虚拟舞台，声波、均衡器与玻璃光轨贯穿整套界面。',
      category: 'character_theme',
      mode: SkinMode.dark,
      seed: Color(0xff39e6d3),
      secondary: Color(0xff9beaff),
      background: Color(0xff04131c),
      backgroundImage: 'assets/themes/miku_digital_stage/bg_miku_wide.png',
      chatBackgroundImage: 'assets/themes/miku_digital_stage/bg_miku_wide.png',
      portraitBackgroundImage:
          'assets/themes/miku_digital_stage/bg_miku_mobile.png',
      immersiveArtwork: true,
      assetManifest: 'assets/themes/miku_digital_stage/manifest.json',
      artworkAlignment: Alignment(.68, -.18),
      backgroundBlur: 0,
      backgroundOpacity: .96,
      overlayOpacity: .05,
      pattern: BackgroundPattern.waves,
      radius: 10,
      elevation: 0,
      material: SkinMaterial.digitalStage,
      animatedBackground: true,
      letterSpacing: .2,
      palette: SkinPalette(
        surface: Color(0xff0b2430),
        recessed: Color(0xff061923),
        raised: Color(0xff123441),
        text: Color(0xffefffff),
        muted: Color(0xffa8cfd3),
        line: Color(0xff299c9a),
        softLine: Color(0xff174f58),
        accent: Color(0xff39e6d3),
        onAccent: Color(0xff032126),
        secondary: Color(0xff8adcf6),
      ),
      metadata: {
        'collection': '角色主题',
        'coverTitle': '未来音阶 · 虚拟舞台',
        'characterName': '初音未来 · Hatsune Miku',
        'characterCaption': '让下一段旋律，成为这次冒险的开场。',
        'subtitle': 'MIKU / 数字舞台 / 青绿声波玻璃',
        'detail': '波形光轨 / 均衡器刻度 / 青绿玻璃 / 虚拟演出空间',
      },
    ),
    ThemeDefinition(
      id: 'teto_clockwork_voice',
      name: '重音发条 · Teto 合成工房',
      description: 'Teto 融入红黑复古合成工房，VU 表、旋钮与机械节拍组成整页 UI。',
      category: 'character_theme',
      mode: SkinMode.dark,
      seed: Color(0xffed4355),
      secondary: Color(0xffffdf9b),
      background: Color(0xff160b0e),
      backgroundImage: 'assets/themes/teto_clockwork_voice/bg_teto_wide.png',
      chatBackgroundImage:
          'assets/themes/teto_clockwork_voice/bg_teto_wide.png',
      portraitBackgroundImage:
          'assets/themes/teto_clockwork_voice/bg_teto_mobile.png',
      immersiveArtwork: true,
      assetManifest: 'assets/themes/teto_clockwork_voice/manifest.json',
      artworkAlignment: Alignment(.72, -.12),
      portraitArtworkScale: 1.32,
      backgroundBlur: 0,
      backgroundOpacity: .96,
      overlayOpacity: .06,
      pattern: BackgroundPattern.scanlines,
      radius: 13,
      elevation: 0,
      material: SkinMaterial.clockworkVoice,
      animatedBackground: true,
      letterSpacing: .16,
      palette: SkinPalette(
        surface: Color(0xff27171b),
        recessed: Color(0xff1a1013),
        raised: Color(0xff382126),
        text: Color(0xfffff3df),
        muted: Color(0xffd4bcb2),
        line: Color(0xff9d3e46),
        softLine: Color(0xff573137),
        accent: Color(0xffed4355),
        onAccent: Color(0xfffff6e6),
        secondary: Color(0xffffd78a),
      ),
      metadata: {
        'collection': '角色主题',
        'coverTitle': '重音发条 · 合成工房',
        'characterName': '重音 Teto · Kasane Teto',
        'characterCaption': '节拍已经上弦，轮到你把故事唱出来了。',
        'subtitle': 'TETO / 复古合成器 / 红黑机械声场',
        'detail': 'VU 表弧线 / 发条旋钮 / 奶油刻度 / 红黑录音工房',
      },
    ),
    ThemeDefinition(
      id: 'default_clean',
      name: '默认简洁',
      description: '清晰留白，跟随系统明暗',
      mode: SkinMode.system,
      seed: Color(0xff486782),
      background: Color(0xff141619),
      radius: 14,
      elevation: 0,
    ),
    ThemeDefinition(
      id: 'cyber_neon',
      name: '赛博霓虹',
      description: '冷青信号、紫电切角，雨夜里的叙事终端',
      mode: SkinMode.dark,
      seed: Color(0xffb99aff),
      secondary: Color(0xff8bdbe4),
      background: Color(0xff080f19),
      backgroundImage: 'assets/skins/cyber_rain.png',
      artworkAlignment: Alignment(0, -.35),
      backgroundBlur: 0,
      pattern: BackgroundPattern.city,
      radius: 14,
      material: SkinMaterial.neon,
      palette: SkinPalette(
        surface: Color(0xff101e2b),
        recessed: Color(0xff0b1723),
        raised: Color(0xff1b2b3d),
        text: Color(0xffe4f3fa),
        muted: Color(0xffa5bdcd),
        line: Color(0xff496477),
        softLine: Color(0xff294356),
        accent: Color(0xff78e4e5),
        onAccent: Color(0xff08242a),
        secondary: Color(0xffc2adff),
      ),
      backgroundOpacity: .85,
      overlayOpacity: .18,
      metadata: {
        'collection': '精修',
        'subtitle': '雨夜频率',
        'detail': '冷青信号 / 切角面板 / 紫电回声',
      },
      animatedBackground: true,
    ),
    ThemeDefinition(
      id: 'deep_space',
      name: '深空星舰',
      description: '星海深处的蓝紫控制台',
      mode: SkinMode.dark,
      seed: Color(0xff8dbdff),
      background: Color(0xff0b1426),
      pattern: BackgroundPattern.stars,
      radius: 14,
    ),
    ThemeDefinition(
      id: 'classic_tavern',
      name: '古典酒馆',
      description: '深胡桃木、古金细框，像翻开一本冒险手记',
      mode: SkinMode.dark,
      seed: Color(0xffd6a84b),
      background: Color(0xff181611),
      backgroundImage: 'assets/skins/tavern_atelier.png',
      artworkAlignment: Alignment(.35, 0),
      backgroundBlur: 0,
      pattern: BackgroundPattern.wood,
      radius: 10,
      material: SkinMaterial.brass,
      palette: SkinPalette(
        surface: Color(0xff2b261e),
        recessed: Color(0xff211e18),
        raised: Color(0xff363027),
        text: Color(0xfff4ead4),
        muted: Color(0xffc8bea7),
        line: Color(0xff766b50),
        softLine: Color(0xff504b38),
        accent: Color(0xffd9b97b),
        onAccent: Color(0xff292519),
        secondary: Color(0xffa9c9b0),
      ),
      backgroundOpacity: .8,
      overlayOpacity: .15,
      metadata: {
        'collection': '精修',
        'subtitle': '炉火与远行',
        'detail': '古金细框 / 胡桃木色 / 炉火暖光',
      },
    ),
    ThemeDefinition(
      id: 'gothic_night',
      name: '暗夜哥特',
      description: '月夜拱窗，酒红与银灰',
      mode: SkinMode.dark,
      seed: Color(0xffef9baa),
      secondary: Color(0xffc7becf),
      background: Color(0xff170e16),
      pattern: BackgroundPattern.arches,
      radius: 10,
    ),
    ThemeDefinition(
      id: 'ink_oriental',
      name: '东方水墨',
      description: '米白纸页、青灰山岚，朱砂只落在重要之处',
      mode: SkinMode.light,
      seed: Color(0xff9e3434),
      background: Color(0xffeeeae0),
      backgroundImage: 'assets/skins/ink_garden.png',
      artworkAlignment: Alignment(0, -.55),
      backgroundBlur: 0,
      pattern: BackgroundPattern.mountains,
      radius: 3,
      elevation: 0,
      material: SkinMaterial.paper,
      palette: SkinPalette(
        surface: Color(0xfffaf7ee),
        recessed: Color(0xffece9de),
        raised: Color(0xfff4f0e5),
        text: Color(0xff283a36),
        muted: Color(0xff525f58),
        line: Color(0xff8b9384),
        softLine: Color(0xffc6c8b8),
        accent: Color(0xff963e32),
        onAccent: Color(0xfffff8eb),
        secondary: Color(0xff3f665e),
      ),
      backgroundOpacity: .8,
      overlayOpacity: .08,
      metadata: {
        'collection': '精修',
        'subtitle': '山间来信',
        'detail': '宣纸层次 / 青灰远山 / 朱砂印记',
      },
    ),
    ThemeDefinition(
      id: 'sakura_dream',
      name: '樱花梦境',
      description: '柔和粉紫，花瓣缓缓飘落',
      mode: SkinMode.light,
      seed: Color(0xff984d83),
      background: Color(0xfffff4f8),
      pattern: BackgroundPattern.petals,
      radius: 22,
      animatedBackground: true,
    ),
    ThemeDefinition(
      id: 'tactical_system',
      name: '战术终端',
      description: '黑灰网格与红色警戒线',
      mode: SkinMode.dark,
      seed: Color(0xffffaaa0),
      background: Color(0xff141719),
      pattern: BackgroundPattern.grid,
      radius: 6,
      elevation: 0,
    ),
    ThemeDefinition(
      id: 'deep_ocean_glass',
      name: '深海玻璃',
      description: '深蓝青绿，低调水波光',
      mode: SkinMode.dark,
      seed: Color(0xff70d5d0),
      background: Color(0xff071d26),
      pattern: BackgroundPattern.waves,
      radius: 20,
      animatedBackground: true,
    ),
    ThemeDefinition(
      id: 'terminal_green',
      name: '终端黑客',
      description: '黑绿终端与轻微扫描线',
      mode: SkinMode.dark,
      seed: Color(0xff81db9a),
      background: Color(0xff061109),
      pattern: BackgroundPattern.scanlines,
      radius: 4,
      elevation: 0,
      fontFamilyPreference: 'monospace',
      animatedBackground: true,
    ),
    ThemeDefinition(
      id: 'oled_black',
      name: 'OLED纯黑',
      description: '纯黑底色，关闭装饰与流光',
      mode: SkinMode.dark,
      seed: Color(0xffb5c8df),
      background: Colors.black,
      backgroundOpacity: 0,
      backgroundBlur: 0,
      overlayOpacity: 0,
      radius: 14,
      elevation: 0,
    ),
    ThemeDefinition(
      id: 'future_white',
      name: '未来白',
      description: '明亮、极简的蓝白科技',
      mode: SkinMode.light,
      seed: Color(0xff245bb5),
      background: Color(0xfff7faff),
      radius: 14,
      elevation: 0,
    ),
  ];
  static ThemeDefinition byId(String? id) => themes.firstWhere(
    (t) => t.id == id,
    orElse: () => themes.firstWhere((t) => t.id == 'default_clean'),
  );
  static List<String> recommend(String context) {
    if (context.contains('圣杯') || context.contains('恐怖')) {
      return ['knight_oath_mooncourt', 'gothic_night', 'classic_tavern'];
    }
    if (context.contains('末日') || context.contains('军事')) {
      return ['tactical_system', 'deep_space'];
    }
    return ['default_clean', 'sakura_dream', 'classic_tavern'];
  }
}
